apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: hugr
    user: hugr
    secureJsonData:
      password: hugr_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600